### ISSUE TITLE
why mdwiki next? 

### ISSUE THREAD

**Issue by liminany** [mdwiki/mdwiki_next#1]
Sorry, I mix up with https://github.com/Dynalon/mdwiki    
What Are they different？ #

**Comment by janbaer** [comment]
Sorry for the late answer I didn't saw the issue before. So the answer is, it's simply my own project for my personal interests. I started MDWiki in 2012 and this is the newest and complete rewritten version. I created MDWiki not only to have my own Wiki, since there're a lot of other Wikis available. I use this project to improve my skills with using web technologies like Node.js, Angular and now React. And by the way I didn't knew about the other project when I started my project and I'm also not sure which project was started before the other...
